# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NumObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('ident', models.IntegerField()),
                ('usersave', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sound', models.FileField(upload_to=b'')),
                ('numobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vapp.NumObject')),
            ],
        ),
    ]
