# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='days',
        ),
        migrations.AddField(
            model_name='blacklist',
            name='fri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='mon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='sat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='sun',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='thurs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='tue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='wed',
            field=models.BooleanField(default=False),
        ),
    ]
